services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=bonds
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testpassword
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=bonds
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testpassword
    depends_on:
      - db