# Generated by Django 4.2.3 on 2023-08-10 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0003_alter_deals_options_alter_rating_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals',
            name='bonds',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='bonds.bonds'),
            preserve_default=False,
        ),
    ]
