# Generated by Django 4.2.3 on 2023-07-13 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BondsRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bonds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('yield_date', models.DateField()),
                ('isin', models.CharField(max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration', models.SmallIntegerField()),
                ('effective_yield', models.DecimalField(decimal_places=2, max_digits=4)),
                ('g_spread', models.DecimalField(decimal_places=2, max_digits=4)),
                ('z_spread', models.DecimalField(decimal_places=2, max_digits=4)),
                ('volume', models.IntegerField(null=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('bonds_rating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bonds.bondsrating')),
            ],
            options={
                'verbose_name_plural': 'Bonds',
            },
        ),
    ]
