# Generated by Django 4.2.3 on 2023-07-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0002_alter_bonds_g_spread_alter_bonds_z_spread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonds',
            name='isin',
            field=models.CharField(default=1, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
